# Generated by Django 2.0.6 on 2019-05-25 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddressInfo',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('consignee', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.CharField(blank=True, db_column='Address', max_length=40, null=True)),
                ('zipcode', models.CharField(blank=True, max_length=20, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('cellphone', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'address_info',
            },
        ),
        migrations.CreateModel(
            name='Booksinfo',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('book_name', models.CharField(blank=True, max_length=40, null=True)),
                ('author', models.CharField(blank=True, max_length=20, null=True)),
                ('publish', models.CharField(blank=True, max_length=40, null=True)),
                ('edition', models.IntegerField(blank=True, null=True)),
                ('printing_time', models.DateField(blank=True, null=True)),
                ('isbn', models.CharField(blank=True, db_column='ISBN', max_length=40, null=True)),
                ('word_number', models.IntegerField(blank=True, null=True)),
                ('page_number', models.IntegerField(blank=True, null=True)),
                ('format', models.CharField(blank=True, max_length=40, null=True)),
                ('paper', models.CharField(blank=True, max_length=40, null=True)),
                ('package', models.CharField(blank=True, max_length=40, null=True)),
                ('price', models.FloatField(blank=True, null=True)),
                ('dd_price', models.FloatField(blank=True, db_column='DD_price', null=True)),
                ('all_numberl', models.IntegerField(blank=True, null=True)),
                ('sales_volume', models.IntegerField(blank=True, null=True)),
                ('arrival_time', models.DateField(blank=True, null=True)),
                ('books_id', models.IntegerField(blank=True, null=True)),
                ('print_num', models.IntegerField(blank=True, null=True)),
                ('publication_date', models.DateField(blank=True, null=True)),
                ('pic', models.CharField(blank=True, max_length=200, null=True)),
                ('series_name', models.CharField(blank=True, max_length=130, null=True)),
                ('customer_grade', models.FloatField(blank=True, null=True)),
                ('market', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'booksinfo',
            },
        ),
        migrations.CreateModel(
            name='OrderList',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('number', models.IntegerField(blank=True, null=True)),
                ('all_price', models.FloatField(blank=True, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'order_list',
            },
        ),
        migrations.CreateModel(
            name='Sort1',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('sort_name', models.CharField(blank=True, max_length=20, null=True)),
                ('books_num', models.IntegerField(blank=True, null=True)),
                ('parent_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'sort1',
            },
        ),
        migrations.CreateModel(
            name='TOrder',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('order_num', models.IntegerField(blank=True, null=True)),
                ('generated_time', models.DateField(blank=True, null=True)),
                ('order_all_price', models.IntegerField(blank=True, null=True)),
                ('state', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 't_order',
            },
        ),
        migrations.CreateModel(
            name='TUser',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.CharField(blank=True, db_column='Email', max_length=40, null=True)),
                ('password', models.CharField(blank=True, max_length=40, null=True)),
                ('user_state', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 't_user',
            },
        ),
        migrations.CreateModel(
            name='Confirm_string',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=256)),
                ('code_time', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dangdangapp.TUser')),
            ],
            options={
                'db_table': 't_confirm_string',
            },
        ),
    ]
